### ISSUE TITLE
load data

### ISSUE THREAD

**Issue by lfb6054** [KvanNoord/3D-CNN-EEG-Emotion-Classification#1]
Hello!How to load data? Format of deap data set 32 * 40 * 40 * 8064？

**Comment by KvanNoord** [comment]
Hi,

You must ask permission for the DEAP dataset at: http://www.eecs.qmul.ac.uk/mmv/datasets/deap/download.html
The script is applied to the "preprocessed" variant and is indeed in 32*40*40*8064 format.

Kind regards,
K. van Noord

**Comment by lfb6054** [comment]
I've downloaded the "deap" dataset, but I really don't know how to download it in "load"_ Data. M "file:
% Load raw data
% Datafile should have size [32, 40, 32, 8064] !!
EEG_ data = load('EEG_ data.mat ');
EEG_ data = EEG_ data.new_ data;
% Load labels
EEG_ labels = load('EEG_ labels');
EEG_ labels = EEG_ labels.EEG_ labels;

How to load 32x40x32x8064 data with this instruction, I think there is a problem.
Thank you for your guidance.

**Comment by KvanNoord** [comment]
Hi,

In that case, the data you've downloaded from the DEAP website should be named "EEG_data.mat" and the labels should be named "EEG_labels". But you can just change the names of the filenames, it doesn't matter. As long as they are put in the form of a 32x40x32x8064 tensor.

32 (subject) x 40 (trials) x 32 (channels) x 8064 (time)

Hope this helps.
